name: Github Actions

on: [push, pull_request]

jobs:
  host-x86:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gcc-12, clang]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build artifact
        env:
          CC: ${{ matrix.compiler }}
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y graphviz jq
          sudo apt-get install -q -y qemu-user
          sudo apt-get install -q -y build-essential
          make clean config
          make check-snapshots || exit 1
          make clean config ARCH=arm
          make check || exit 1
          make clean config ARCH=riscv
          make check || exit 1

  coding_style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            .ci/check-newline.sh
            .ci/check-format.sh
      shell: bash
